# Generated by Django 3.1.4 on 2020-12-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_disciplina', models.CharField(default=None, max_length=7, verbose_name='codigo disciplina')),
                ('nome_disciplina', models.CharField(default=None, max_length=50, verbose_name='nome dsiciplina')),
                ('curso', models.CharField(default=None, max_length=50, verbose_name='Curso')),
                ('professor', models.CharField(default=None, max_length=50, verbose_name='professor')),
            ],
            options={
                'ordering': ('codigo_disciplina',),
            },
        ),
    ]
