# Generated by Django 3.1.4 on 2020-12-16 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MonitoreEW', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aluno', models.CharField(default=None, max_length=60, verbose_name='Nome do aluno')),
                ('matricula_aluno', models.CharField(default=None, max_length=11, verbose_name='Matricula')),
                ('monitor', models.BooleanField(default=False)),
                ('disciplinas_matriculadas', models.ManyToManyField(to='MonitoreEW.Disciplina')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('nome_aluno',),
            },
        ),
    ]
