# Generated by Django 3.1.4 on 2020-12-16 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MonitoreEW', '0002_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='monitoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField(default=None)),
                ('data', models.DateField(default=None)),
                ('local', models.CharField(default=None, max_length=200, verbose_name='local')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonitoreEW.aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MonitoreEW.disciplina')),
            ],
            options={
                'ordering': ('data',),
            },
        ),
    ]
